// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUsTbASIVWIJATawCsyBJmvSrGoqaUuds',
    appId: '1:889015894946:web:6a83750624a548f81868fb',
    messagingSenderId: '889015894946',
    projectId: 'my-todo-app-550ba',
    authDomain: 'my-todo-app-550ba.firebaseapp.com',
    storageBucket: 'my-todo-app-550ba.firebasestorage.app',
    measurementId: 'G-PF350K8YG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwImDYJvYVVL7uT7YSWrjxBxZ5bQhxe6U',
    appId: '1:889015894946:android:b32e6244cd360d5c1868fb',
    messagingSenderId: '889015894946',
    projectId: 'my-todo-app-550ba',
    storageBucket: 'my-todo-app-550ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW0gxuNyOI5JSRx5JeITCGChZZLGStrdA',
    appId: '1:889015894946:ios:58b9cc9d3bb004e91868fb',
    messagingSenderId: '889015894946',
    projectId: 'my-todo-app-550ba',
    storageBucket: 'my-todo-app-550ba.firebasestorage.app',
    iosBundleId: 'com.riyaz.myTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW0gxuNyOI5JSRx5JeITCGChZZLGStrdA',
    appId: '1:889015894946:ios:58b9cc9d3bb004e91868fb',
    messagingSenderId: '889015894946',
    projectId: 'my-todo-app-550ba',
    storageBucket: 'my-todo-app-550ba.firebasestorage.app',
    iosBundleId: 'com.riyaz.myTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUsTbASIVWIJATawCsyBJmvSrGoqaUuds',
    appId: '1:889015894946:web:0bf298f706976e1c1868fb',
    messagingSenderId: '889015894946',
    projectId: 'my-todo-app-550ba',
    authDomain: 'my-todo-app-550ba.firebaseapp.com',
    storageBucket: 'my-todo-app-550ba.firebasestorage.app',
    measurementId: 'G-JHQ50256WM',
  );
}
